PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

select distinct ?ont ?class where {
   { GRAPH ?g {
      VALUES ?onttype {owl:Ontology skos:ConceptScheme}
      ?ont a ?onttype .
      ?class a ?thing .
   }
    ?thing rdfs:subClassOf{1,6} rdfs:Class .
  FILTER ( !isBlank(?class) )
} UNION {
GRAPH ?g {
      VALUES ?onttype {owl:Ontology skos:ConceptScheme}
      ?ont a ?onttype .
      ?class a rdfs:Class .
   }
  FILTER ( !isBlank(?class) )
}
} LIMIT 1000000
